"""production migration

Revision ID: 60a8ce084d6e
Revises: 
Create Date: 2025-05-07 19:49:41.639828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60a8ce084d6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shipments_id', table_name='shipments')
    op.drop_table('shipments')
    op.drop_index('ix_shipment_items_id', table_name='shipment_items')
    op.drop_table('shipment_items')
    op.alter_column('users', 'birthdate',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_column('users', 'is_social_account')
    op.drop_column('users', 'social_provider')
    op.drop_column('users', 'facebook_id')
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('facebook_id', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('social_provider', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('is_social_account', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
    op.alter_column('users', 'birthdate',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.create_table('shipment_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shipment_id', sa.INTEGER(), nullable=True),
    sa.Column('design_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shipment_items_id', 'shipment_items', ['id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('tracking_number', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('shipped_date', sa.DATETIME(), nullable=True),
    sa.Column('estimated_delivery_date', sa.DATETIME(), nullable=True),
    sa.Column('delivered_date', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shipments_id', 'shipments', ['id'], unique=False)
    # ### end Alembic commands ###
